### ISSUE TITLE
Publish PGL as a NPM package

### ISSUE THREAD

**Issue by abhishektiwari** [range-et/PGL#1]
PGL is not distributed as NPM package, that to me seems a very inconvenient way to consume a TypeScript package. Publishign as NPM package is a few hours of work [as described here](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages).

[Joss Review](https://github.com/openjournals/joss-reviews/issues/5887)

**Comment by range-et** [comment]
Now published as an NPM package : https://www.npmjs.com/package/plebiangraphlibrary
Also a boilerplate project is available here: https://github.com/range-et/pgl_example
