### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by abhishektiwari** [range-et/PGL#2]
Add clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. [Here](https://github.com/range-et/PGL/community)'s how this project compares to [recommended community standards](https://opensource.guide/).

[Joss Review](https://github.com/openjournals/joss-reviews/issues/5887)

**Comment by range-et** [comment]
Added in community guidelines and a code of conduct
