### ISSUE TITLE
Add  automated tests to catch regressions

### ISSUE THREAD

**Issue by abhishektiwari** [range-et/PGL#3]
SDKs/Packages need to set higher bar wrt to quality and tests. How will one catch regressions before releasing a new version? Test can be as simple as taking Screenshot of render of examples included and performing image diff against a refrence image.

[Joss Review](https://github.com/openjournals/joss-reviews/issues/5887)

**Comment by range-et** [comment]
Added in a regression test as outlined in the JOSS review
